

=== Datenaufbereitung

Die zu verwendenden Daten stehen als 24 Exceltabellen zur Verfügung. Für jedes Jahr, jede Region und SRF/andere gibt es eine Tabelle im `wide` Format. Das bedeutet, jeder Zeitschienenwert hat eine Zeile mit allen Kombinationen aus Sender und Metrik in eigenen Spalten. Für die Filterung nach spezifischen Kombinationen ist das `long` Format nötig, in dem jede Zeile aus der `wide` Tabelle eine eigene Zeile bekommt.

Zusätzlich werden die Daten so aufbereitet, dass sie besser von einem LLM verarbeitet werden können. Zum Beispiel werden Regionenkürzel wie `DS` zu `Deutschschweiz` und Namen der Kenngrössen ausgeschrieben. Ziel ist der sonst notwendige Mapping-Schritt im Verarbeitungsauftrag des LLMs überspringen zu können und so Missverständnisse zu reduzieren.

Als Output der Datenaufbereitung wird eine `.parquet`-Datei geschrieben, die dem MCP-Server bereitstellt wird.

=== MCP Server

Im Rahmen der Arbeit wurden zwei Versionen des MCP Servers entwickelt. Version eins verwendet ein komplexes System aus aus Richtlinien, Katalogen erlaubter Daten und Validierung um die Anfragen zu prüfen und um nur erlaubte Aktionen auszuführen. Diese Komplexität führte in ersten Tests dazu, dass der Agent mehrere Anfragen stellen musste, bis die Anfrage dem Schema entsprach. Mit der verwendeten Datenaufbereitung stellte sich weiter die Herausforderung, dass oft keine Daten zurückgegeben wurden, weil die Selektion und Filter trotz Validierung und Schema nicht wie gewünscht war. In dieser Form war der Chatbot nicht verwendbar. Diese Version wird für die Evaluierung daher nicht in Betracht gezogen.

Version zwei basiert auf den daraus gewonnenen Erkenntnissen. Statt über ein eigenes Tool, wird das Glossar mit Fachbegriffen der TV-Forschung (Marktanteil, Rating, Nettoreichweite, Sehdauer, etc.) als Ressource bereitgestellt und direkt bei der Initialisierung einer MCP-Session geladen. Die Daten können über das Tool `abfrage_jahresbericht` in strukturierter Form abgefragt werden. Es erlaubt die Filterung nach Jahr, Region, Zeitschiene, Kenngrösse und Sender und unterstützt Sortierung und die Erstellung von Pivot-Tabellen. Als Ergebniss gibt das Tool eine Markdown-Tabelle zurück. Diese kann vom Agent einfacher verarbeitet werden als zum Beispiel Daten, die im `json` Format zurückgegeben werden. In ersten Test funktioniert dieser MCP-Server viel besser und liefert in der Regel im ersten Versuch die gewünschten Daten.
