
=== System-Prompt
Damit der LLM-Agent funktionieren kann, wird dem LLM zusätzlich zu den Benutzereingaben und gegebenenfalls der Chat Historie eine vordefinierte Instruktion der System-Prompt mitgegeben. Ein System-Prompt gibt dem LLM definierte Anweisungen, wie die Tools genutzt oder die Antworten formuliert werden sollen. Da von deutschen Eingaben ausgegangen wird, ist sie auf Deutsch definiert. Es wird eine Identität und ein Ablauf definiert. Als Identität wird die Rolle «Datenassistent für die Analyse» definiert. Der Ablauf hat einen «Abfragen» und einen «Antworten» Bereich. Im Abfragen-Bereich wird als erstes beschrieben, dass das `abfrage_jahresbericht`-Tool aufgerufen werden soll, sowie wie mit dem Tool umzugehen ist. Es enthält Informationen zu Standardwerten, Spaltenbeschreibungen sowie Sortierungsmöglichkeiten. Der Antworten-Bereich enthält Instruktionen, wie der Chatbot Antworten mit oder ohne Daten formulieren soll. Die vollständige System-Prompt kann im GitHub Repository unter `poc/apps/chatbot/src/chatbot/system_prompt_v2_minimum.py` nachgelesen werden cite:[githubRepoTransferarbeit].
