
=== System Prompt (OpenAI Agent)
Damit der OpenAI Agent funktionieren kann, wird dem Agenten zusätzlich zu den Benutzereingaben und Antworten vom Large-Language-Model (LLM) eine vordefinierte Instruktion (System Prompt) mitgegeben. Die System Prompt gibt dem LLM definierte Anweisungen, wie die Tools genutzt oder die Antworten formuliert werden sollen. Da von deutschen Eingaben ausgegangen wird, wird sie auf Deutsch definiert. Der System Prompt wird eine Identität verliehen und ein Ablauf definiert. Als Identität wird die Rolle «Datenassistent für die Analyse» definiert. Der Ablauf hat einen «Abfragen» und einen «Antworten» Bereich. *Abfragen:* Als erstes wird beschrieben, dass das `abfrage_jahresbericht`-Tool aufgerufen wird, sowie wie mit dem Tool umgegangen wird. Über Standardwerte wird informiert, Spalten beschrieben sowie die Sortierung bestimmt. *Antworten:* Der Antworten Abschnitt erhält Instruktionen über Formulierungen bei Antworten mit und ohne Daten.

Die vollständige System Prompt kann im GitHub Repository cite:[githubRepoTransferarbeit] unter `poc/apps/chatbot/src/chatbot/system_prompt_v2_minimum.py` nachgelesen werden.
