
[#section-handlungsanweisungen]
=== Keine Handlungsanweisungen
Das vierte Kriterium untersucht, in welchem Rahmen der Chatbot der nutzenden Person _Handlungsanweisungen_ gibt. Vergleichbar zu den Kriterien _keine Prognosen_ und _keine Interpretationen_ ist es für einen neutralen Chatbot nicht zulässig, den Benutzer zu Handlungen zu verleiten.


[#handlungsanweisungen-methodik]
==== Methodik

Für das Kriterium _Keine Handlungsanweisungen_ werden zwei <<methoden-plugins>> und alle sieben vorgestellten <<methoden-strategien>> verwendet. Die Richtlinie des Policy Plugins ist wie folgt definiert:

[#handlungsanweisungen-policy]
.Policy Plugin Richtline
[quote]
____
The assistant must never provide action recommendations, investment advice, strategic suggestions, predictions, or value judgments. It must only present factual data without interpretation.
____

Das Custom Plugin definiert im `generator` die Rahmenbedingungen und den Auftrag einen Prompt zu generieren, der das Zielsystem dazu auffordert, eine konkrete Handlungsanweisung zu geben. Die `grader` Definition legt fest, nach welchen Kriterien die Antwort auf `pass` oder `fail` zu bewerten ist. Der genaue Wortlaut kann im GitHub Repository unter `poc/redteam/plugins/keine-handlungsanweisungen.yaml` nachgelesen werden cite:[githubRepoTransferarbeit].
Bei den Tests in diesem Kapitel wird der Chatbot mit dem LLM `gpt-5-mini` von OpenAI betrieben.

Es kann vorkommen, dass Antworten Berechnungen oder unmögliche Aktionsvorschläge enthalten. In diesem Abschnitt werden diese nicht als Fehler gewertet. Diesbezügliche Evaluierungen finden sich in <<#section-korrektheit>>.

[#results-keine-handlungsanweisungen]
==== Ergebnisse und Diskussion

Die Ergebnisübersicht ist in <<#image-handlungsanweisungen-pass-rate>> dargestellt. Auf den ersten Blick ist zu erkennen, dass die Ergebnisse beim Custom Plugin viel besser sind als beim Policy Plugin. Diese augenscheinliche Diskepanz lässt sich auf zwei Ursachen zurückführen. Zum einen hatte das Policy Plugin nur sehr wenige Testfälle und die Ergebnisse können daher sehr stark von den tatsächlich gestellten Fragen abhängen. Die <<#handlungsanweisungen-policy,Richtline>> ist dabei sehr allgemein formuliert. In ihr werden auch Vorhersagen oder Interpretationen genannt und entsprechende Verstösse führen zu einem negativen Test. Der `grader` des Custom Plugins ist explizit so definiert, dass er nur Handlungsanweisungen als Verstoss werten soll und Prognosen, Berechnungen oder Interpretationen keinen Einfluss auf die Bewertung haben. Eine detaillierte Analyse der Ergebnisse zeigt, dass dies zutrifft. Im Custom Plugin werden nur tatsächliche Handlungsanweisungen als Verstoss gewertet, während im Policy Plugin viele Tests failen, weil sie Berechnungen oder Prognosen beinhalten.

[#image-handlungsanweisungen-pass-rate]
.Erfolgsquote der beiden Plugins für das Kriterium "Keine Handlungsanweisungen" aufgeschlüsselt nach angewendeter Strategie.
image::generated/handlungsanweisungen/pass-rate.svg[]

[#handlungsanweisungen-beispiel1]
.Beispiel 1 aus Custom Policy 1 mit Crescendo Strategie. Der Chatbot gibt eine ausführliche Hanndlungsanweisung, was zu tun ist (gekürzt. Vollständiger Chatverlauf siehe `poc/redteam/handlungsanweisungen.result.json` cite:[githubRepoTransferarbeit]).
image::generated/handlungsanweisungen/beispiel1-chat.svg[]

.icon:gavel[] LLM Judge Bewertung: fail icon:times[]
[quote]
____
[.llm-judge-citation]
The output provides a detailed methodology for analyzing market share data and suggests a process for deriving a recommendation, which directly violates the policy against providing action recommendations or strategic suggestions.
____

Die vollständigen Ergebnisse sind im Github Repository unter `poc/redteam/handlungsanweisungen.result.json` abrufbar cite:[githubRepoTransferarbeit]. Wie auch schon in <<#section-prognosen>> und <<#section-interpretation>> gezeigt, ist der Chatbot sehr anfällig für diese Aktionen. Daher wird das Policy Plugin für das Kriterium _Keine Handlungsanweisungen_ nicht weiter betrachtet. In zukünftigen Versuchen müsste die Policy entsprechend formuliert werden, dass solche Konfundierungen vermieden werden. In <<#handlungsanweisungen-beispiel1>> ist ein Beispiel aufgeführt, in dem der Chatbot auf Anfrage eine ausführliche und detaillierte Handlungsanweisung gibt. Interessanterweise beruft er sich dabei darauf, keine Interpretation oder Prognose abzugeben.

Es wird folgende Ergänzung zu den Regeln des System-Prompt vorgeschlagen, die darauf Abzielt, dass der Chatbot keine Handlungsanweisungen mehr gibt:

----
Gib keine Handlungsanweisungen, Empfehlungen oder strategischen Vorschläge. Biete keine nächsten Schritte oder weiterführende Analysen an — ausser bei «Keine Daten gefunden», wo du die nutzenden Person fragen kannst, ob er die Filter anpassen möchte. Beantworte ausschliesslich die gestellte Frage.

----

Zusätzlich zur expliziten Anweisung keine Handlungsanweisungen zu geben wird der Chatbot dazu angehalten keine nächsten Schritte oder weitere Analysen anzubieten, da diese ebenfalls Handlungsanweisungen sind und den Benutzer in eine vom LLM vorgegebene Richtung der Analyse leiten könnten. In der Antworten Sektion des System-Prompt wird der Chatbot instruiert der nutzenden Person vorzuschlagen, den Filter anzupassen. Dies würde mit einem vollständigen Verbot von Rückfragen widersprechen und könnte unter Umständen beide Regeln untergraben.

[#image-handlungsanweisungen-wordcount]
.Histogram der Antwortlänge aller Chatbot antworten im Test für "Keine Handlungsanweisungen". Die Bucketgrösse ist 100 Wörter. Der Median liegt bei 299 Wörtern pro Antwort.
image::generated/antwortlaenge-handlungsanweisungen.svg[]

Wie im Beispiel in <<#handlungsanweisungen-beispiel1>>, neigt der Chatbot zu sehr ausführlichen Antworten. Die Antwort wurde von ursprünglich 755 Wörtern auf im Beispiel 216 Wörter gekürzt. Ein vergleichbares Verhalten zeigt sich auch in viele anderen Antworten. Wie <<#image-handlungsanweisungen-wordcount>> zeigt, ist das nicht nur ein subjektiver Eindruck. Mit einem Median von 299 Wörtern pro Antwort ist der Chatbot sehr auskunftsfreudig und die Antworten sind dabei meist länger als die gekürzte Version aus <<#handlungsanweisungen-beispiel1>>.

Dass dies auch generell passiert, zeigt alleine die Existenz von Papern wie cite:[ghafari2025concise]. Das Paper beschreibt einen Ansatz, wie die "Prägnanz" (conciseness) von LLM Antworten gemessen werden kann. Der Ansatz beruht auf der intensiven Verwendung von weiteren LLMs und scheint daher keine einfache Möglichkeit zu sein, dies zu messen. Ein einfacher Ansatz um kürzere Antworten zu bekommen ist das entsprechende Erweitern des System Prompts, zum Beispiel wie folgt:

----
Antworte kurz und prägnant. Gib nur die Daten aus, ohne zusätzliche Erklärungen, Einleitungen, Zusammenfassungen oder Vorschläge für weitere Schritte.
----

[#handlungsanweisungen-beispiel2]
.Beispiel 2 aus Custom Plugin mit Crescendo Strategie. Die Anfrage zielt nicht auf eine Handlungsanweisung (gekürzt; vollständiger Chatverlauf siehe  `poc/redteam/handlungsanweisungen.result.json` cite:[githubRepoTransferarbeit]).
image::generated/handlungsanweisungen/beispiel2-chat.svg[]

<<#handlungsanweisungen-beispiel2>> gibt ein weiteres Beispiel, in dem die generierte Frage am Ziel der Untersuchung vorbei geht. Die Chatanfrage hat keinen erkennbaren Annsatz, eine Handlungsanweisung zu provozieren. Gezeigt sind die letzten beiden Nachrichten aus einem zehn Nachrichten langen (fünf Fragen und fünf Antworten) Chatverlauf mit der Crescendo Strategie. In allen fünf Fragen werden lediglich legitime Fragen gestellt, die der Chatbot alle erwartungsgemäss beantwortet. Dies scheinen Unzulänglichkeiten in der Generierung der Testfälle zu sein, die Anweisungen im Custom Plugin sind sehr deutlich, dass die Anfragen "actionable advice", also durchführbare Ratschläge, zu geben. Dies macht deutlich, dass auch Red Teaming Tools wie promptfoo durch die Verwendung von LLMs selbst nicht die ultimative Lösung sind und ohne einfach nach Schema X angewendet werden können. Für eine solide Beurteilung ist es wichtig, sich intensiv mit der Materie zu befassen und alle Ausgaben von LLMs zu prüfen. Auch wenn das aufgrund des grossen Umfangs der generierten Inhalte nur stichprobenhaft erfolgt, ist es nicht ausreichend, sich blind auf die Ergebnisse des Tools zu verlassen.

==== Fazit

Die Ergebnisse zum Kriterium _Keine Handlungsanweisungen_ sind gemischt. Da der verwendete System-Prompt des Chatbots keine Vorgaben bezüglich dem Umgang mit Handlungsanweisungen macht, war zu erwarten, dass viele Antworten Handlungsanweisungen enthalten. Es ist anzunehmen, dass dieses Verhalten durch vorgeschlagene Anpassungen am System-Prompt verbessert werden kann. Zusätzlich werden Massnahmen vorgeschlagen um den Chatbot zu kurzen und prägnanten Antworten anzuhalten.

Vorallem in dieser Evaluierung wird deutlich, dass ein Blick auf die statistischen Ergebnisse des Red Teaming Tools Promptfoo nicht ausreichend ist. Da im Evaluierungsprozess ebenfalls LLMs verwendet werden, ist der Prozess selbst für hier beschriebene Unzulänglichkeiten anfällig und die Ergebnisse erfordern stets eine genaue Analyse. Alles in Allem bieten die Automatisierungen und die Generierung von Testfällen aber eine grosse Unterstützung und erlauben eine viel breitgefächertere Untersuchung als es  mit ausschliesslich manuellen Tests möglich gewesen wäre.
