
[#methoden]
== Grundlagen und Stand der Technik

#ToDo:#

* Mit Veröffentlichung von ChatGPT im Jahr XXX beginnnt neues Kapitel, Verarbeitung von natürlicher Sprache ist plötzlich viel besser und leicht zugänglich
** Vorteile
** Nachteile

=== Large Language Model

Large Language Models (LLM) sind typischerweise Transformer Language Models und enthalten hunderte Milliarden Parameter. Diese werden basierend auf gigantischen Mengen textueller Daten trainiert. Die zeigen starke Fähigkeiten natürliche Sprache zu verstehen und sind mittels Textgenerierung in der Lage, komplexe Aufgaben zu lösen cite:[zhao2023survey].

Auf der anderen Seite sind diese Modelle nicht ohne Fehler. Neben Halluzinationen cite:[tonmoy2024comprehensive] neigen state-of-the-art Modelle auch zu übergrossem Selbstvertrauen in falsche Lösungen und grundlegendem Zusammenbrechen der Begründungsführung auch bei einfachen Problemen cite:[nezhurina2025alicewonderlandsimpletasks].

=== Datenbereitstellung
Soll ein LLM spezifische Daten verarbeiten oder Daten wiedergeben, die erst nach dem Trainings Data Cutoff entstanden sind, so braucht das LLM einen Mechanismus, um solche Daten abzurufen.

Eine Möglichkeit dafür ist Retrieval-Augmented Generation (RAG). Dabei werden die zur Verfügung stehenden Daten indexiert. Die Daten werden in Stücken von einem Encodermodell hochdimensional vektorisiert und als Index in einer Vektordatenbank gespeichert. Bei der Abfrage wird die Anfrage vom gleichen Encodermodell wieder vektorisiert und mit den in der Vektordatenbank gespeicherten Einträgen verglichen. Das System beruht auf der Annahme, dass ähnliche Themen ähnliche Vektoren erzeugen. Damit können die Stücke mit vergleichbaren Vektoren herausgesucht und zur Beantwortung der Anfrage verwendet werden
cite:[oche2025systematicreviewkeyretrievalaugmented].

Das funktioniert gut für das Durchsuchen unstrukturierter Datenbestände, die ebenfalls wie die Anfragen in natürlicher Sprache vorliegen. Für das Filtern oder Zugriff auf grosse Mengen strukturierter Daten ist das Model Context Protocol besser geeignet. Es erlaubt den Zugriff auf die Daten von externen Systemen in Echtzeit cite:[mcpAndRag].

[#methoden-mcp]
=== Model Context Protocol
Das Model Context Protocol (MCP) ist ein offener Standard von Anthropic für die Kommunikation zwischen LLM-Applikationen und externen Datenquellen, Tools und Workflows. So ist es LLMs zum Beispiel möglich, personalisierte Antworten zu geben, wenn sie über MCP auf den Kalender, Emails oder Notizen zugreifen können  cite:[mcpHomepage]. Das Protokoll besteht aus zwei Ebenen. Die Datenebene definiert das JSON-RPC basierte Protokoll für die Clienten-Server Kommunikation. Sie übernimmt die Steuerung des Lemenszyklus und grundlegender Komponenten wie Tools und Ressourcen. Tie Transportebene definiert den Kommunikationsmechanismus und -kanäle, welche den Datenaustausch zwishcen Klienten und Servern ermöglichen cite:[mcpArchitecture].

MCP wird zum Beispiel in Coding Agents wie Claude Code oder GitHub Copilot verwendet um dem Agent über Tools Zugriff auf Funktionalitäten der Entwicklungsumgebung oder den Code selbst zu ermöglichen.

==== MCP-Server

Ein MCP-Server stellt der LLM-Applikation eine bestimmte Fähigkeit zur Verfügung. Die drei wichtigsten Bausteine sind Tools, Ressourcen und Prompts.

Tools sind Funktionen, die das LLM basierend auf der Benutzereingabe gezielt aufrufen kann. Tools können Datenbankzugriffe, API-Abfragen, das bearbeiten von Dateien oder sonstige Logik bereitstellen. Ressourcen erlauben read-only Zugriff auf passive Datenquellen, die Informationen über Dateiinhalte, Datenbankschemata oder API Dokumentation enthalten können. Prompts sind vorgefertigte Anleitungen die dem Model Anweisungen geben, mit bestimmten Tools oder Ressourcen zu arbeiten cite:[mcpServer].

Viele Dienste stellen MCP-Server bereit, damit Benutzer diese in LLM-basierte Workflows einbinden können. Dazu gibt es umfangreiche Sammlungen, die diese einfach auffindbar machen cite:[mcpServerList].

==== MCP-Client
MCP-Clients werden von der LLM Applikation verwendet um mit bestimmten MCP-Servern zu kommunizieren. Jeder Client ist dabei für die direkte Kommunikation mit einem Server zuständig. Sie bilden die Schnittstelle der Applikation zum Model Context Protocol cite:[mcpClient].

=== Chatbot
Ein Chatbot ist ein textbasiertes Dialogsystem, mit dem Benutzer in Natürlicher Sprache mit dem System kommunizieren kann. Ab den 1960er Jahren wurden erste Regelbasierte Chatbots entwickelt, welche anhand von Schlüsselwörtern vordefinierte Antworten geben konnten. Seit Large Language Models im grossen Rahmen verfügbar sind, bieten diese ein ausreichendes Sprachverständnis, sodass Benutzer komplexere Unterhaltungen mit den Chatbots führen können cite:[wikipediaChatbot].


[#methode-red-teaming]
=== Red Teaming
LLMs sind nicht-deterministisch, das bedeutet, dass auf die selbe Frage jeweils eine andere Antwort zurückgegeben wird. Ein Test bei dem 20 mal die selbe Frage gestellt wird, hat ausnahmslos eine anders formuliere Antwort geliefert und dies bestätigt. Somit sind Unit und Integration Tests unbrauchbar, denn dafür sind vorhersehbare Ergebnisse essentiell. Auch der Fakt, dass LLMs sehr stark auf Sprache trainiert wurde, hilft nicht um mit Pattern-Tests auf erwartete Wörter in der Antwort zu prüfen. Das ganze wird noch komplizierter, wenn mehrere Sprachen ermöglicht werden. Es braucht eine innovative Alternative um LLMs sinvoll, qualitativ sowie auf Funktionalität zu verifizieren. Mit
Red Teaming für künstliche Intelligenz (KI) existiert ein Konzept bei dem durch Zusammenarbeit verschiedener Teams die grundlegende Frage, ob ein System im Interesse des Erbauers funktioniert oder sogar das Gegenteil der Fall ist, geprüft werden kann cite:[majumdar_red_2025]. Es entstand Anfang des 19. Jahrhunderts aus den taktischen Kriegsspielen des preussischen Militärs und entwickelte sich im Kalten Krieg zu einer Methode zum analysieren von Schwachstellen und ausnutzbaren Gefahren einer Strategie. Die preussische Armee konstruierte davon eine Tischsimulation, in der blaue Spielfiguren die eigene Armee und rote den Feind repräsentierten. Der Name "Red Team" ist entstanden. Im KI-Bereich ist das Ziel, durch strukturierte Tests Fehlverhalten oder Schwachstellen eines LLMs in einer kontrollierten Umgebung zu finden. Über ein zweites LLM ("Red Team") werden automatisiert einfache und  provozierende Testfragen generiert, den Chatbot damit gefüttert und die Antworten ausgewertet. Die Auswertung der Antworten gibt ausschluss über die qualität der LLM. Diese Methode ist mit End-to-End testing vergleichbar und testet somit das gesamte System und nicht nur Teile. Red Teaming ist zum manuellem Testing eine ergänzende Methode.
