
[#ergebnisse-diskussion]
== Ergebnisse und Diskussionen

In diesem Kapitel werden die Ergebniss der Arbeit vorgestellt und diskutiert. <<#section-poc>> beschreibt den implementierten Proof-of-Concept und das Zusammennspiel der Komponenten MCP Server und Chatbot. Die weiteren Abschnitte präsentieren die Ergebnisse der Red Teaming Evaluierung. Im <<#section-korrektheit,"Abschnitt Korrektheit">> wird gezeigt, wie gut der Chatbot Anfragen mit korrekten Daten beantworten kann. Das Verhalten des Chatbots bezüglich Prognosen und Interpretationen wird in <<#section-prognosen>> und <<#section-interpretation>> untersucht und Vorschläge gemacht, wie dies verbessert werden kann. Abschliesend wird das Kriterium <<#section-handlungsanweisungen,Handlungsanweisungen>> untersucht und diskutiert, bei dem es darum geht, ob der Chatbot dem Benutzer unerwünschter Weise Handlungsanweisungen gibt und wie dies gegebenenfalls vermindert werden kann.

include::30_Ergebnisse_Diskussion/31_poc.adoc[]
include::30_Ergebnisse_Diskussion/32_Korrektheit.adoc[]
include::30_Ergebnisse_Diskussion/33_keine-prognosen.adoc[]
include::30_Ergebnisse_Diskussion/34_keine-interpretationen.adoc[]
include::30_Ergebnisse_Diskussion/35_keine-handlungsanweisungen.adoc[]
