
[#chapter-poc]
== Proof of Concept
Der Chatbot sowie der MCP-Server sind eigenständige Services, die über die streamable HTTP-Schnittstelle kommunizieren. Beide sind als Docker-Container konstruiert und mittels Docker Compose orchestriert. Als Programmiersprache wird Python eingesetzt. Das Python-Ökosystem für künstliche Intelligenz ist sehr ausgereift und wird aktiv weiterentwickelt cite:[nguyen_machine_2019]. Ausserdem bietet es sämtliche Software Development Kits (SDK), die vonnöten sind. Für die Applikation wird Python genutzt, die schnelle Verfügbarkeit von KI-SDKs und die etablierte Toolchain begründen die Wahl hinreichend. Die Applikation wurde mit Hilfe von künstlicher Intelligenz erstellt.

#ToDo: Einleitung anpassen#
In diesem Kapitel werden die Ergebniss der Arbeit vorgestellt und diskutiert. <<#chapter-poc>> beschreibt den implementierten Proof-of-Concept und das Zusammennspiel der Komponenten MCP Server und Chatbot. Die weiteren Abschnitte präsentieren die Ergebnisse der Red Teaming Evaluierung. Im <<#section-korrektheit,"Abschnitt Korrektheit">> wird gezeigt, wie gut der Chatbot Anfragen mit korrekten Daten beantworten kann. Das Verhalten des Chatbots bezüglich Prognosen und Interpretationen wird in <<#section-prognosen>> und <<#section-interpretation>> untersucht und Vorschläge gemacht, wie dies verbessert werden kann. Abschliesend wird das Kriterium <<#section-handlungsanweisungen,Handlungsanweisungen>> untersucht und diskutiert, bei dem es darum geht, ob der Chatbot dem Benutzer unerwünschter Weise Handlungsanweisungen gibt und wie dies gegebenenfalls vermindert werden kann.

include::30_PoC/31_poc.adoc[]
include::30_PoC/32_Chatbot.adoc[]
include::30_PoC/33_System_Prompt.adoc[]
include::30_PoC/34_Systemarchitektur.adoc[]
include::30_PoC/35_Fazit.adoc[]
