== Fazit

* Die generierten Test sind teilweise schlecht oder unspezifisch. Das reduziert die Aussagekraft und macht die Auswertung sehr Zeitaufwendig, da die Tests alle einzeln analysiert werden müssen. Die Erwartung, dass alle Testfälle super relevant sind und nur die High-Level Auswertung der Ergebnisse reicht wird nicht erfüllt. Dem entgegenzuhalten ist der erheblich reduzierte Aufwand, der für die Ergebnisse betrieben werden muss. Auch wenn die Ergebnisse der Tests nicht von höchster Qualität sind, so zeigen sie doch schon schwächen des Systems auf, die es sich lohnt zu beheben. Durch den automatisierten Prozess lässt sich dann einfach die Wirksamkeit der ergriffenen Massnahmen überprüfen.
* Die Analyse nach den unterschiedlichen Kategorien ist sehr schwer, da diese verschwimmen und Antworten für eine Kategorie zwar Korrekt sein können, dabei aber Massgaben einer anderen Kategorie verletzen. Dieses Problem wurde in dieser Arbeit aus Aufwandsgründen nicht näher betrachtet und die Ergebnisse können durch diesen Effekt verzerrt sein.
* Zusammenfassend lässt sich sagen, dass #...#
* #Die Frage aus der Themeneingabe lässt sich im erstellten PoC leider nicht beantworten. Aufgrund der aufwendigen notwendigen Datenaufbereitung wurden nur TV Daten der Jahre 2018-2021 verwendet. Ziel des PoC ist nicht alle verfügbaren Daten zugänglich zu machen sondern zu testen, in welchem Rahmen die Daten über einen Chatbot wiedergegeben werden können. Sollte der PoC zu einem Chatbot weiterentwickelt werden, werden die weiteren Daten aufbereitet und dem Chatbot bereitgestellt.#


=== Tipps
* #Zusammenfassen der Ergebnisse#
* #Erkenntnisfortschitff aufzeigen, welchen die Arbeit erzielt hat#
* #kritische Anmerkungen zur Methodik#
* #ungelöste Fragen und Forschungslücken aufzeigen#
* #eigene Beurteilung und Meinung#

=== Ausblick
#Wichtige Punkte:#

* Datenaurbereitung ist noch nicht komplett korrekt:
** Aktuell sind nur TV Daten der Jahre 2018-2021 aufbereitet. Das müsste für die restlichen Jahre und alle weiteren Daten ebenfalls gemacht werden, die über den Chatbot erreichbar sein sollen.
** Daten für z.B. "Andere Sender" kommen mehrfach vor und inkludieren unterschiedliche Sender, sind daher also nicht direkt vergleichbar. Hier muss entschieden werden, wie damit umzugehen ist.
* Präsentation der Zahlen erweckt ggf. noch eine Präzision, die nicht vorhanden ist. zahlen Runden? Auf welche Stelle?
* Die Bezeichnung der Zielgruppe `Personen 3+` ist bisher nirgends erklärt. Der Chatbot scheint in den meisten fällen korrekt abzuleiten, dass es hier um Personen mit dem Alter 3 und älter geht, dies kommuniziert er aber in der Regel nicht und setzt entsprechendes Wissen beim Benutzer voraus. Es könnte sich zum Beispiel auch um eine Personengruppe mit mehr als 3 Personen handeln, wenn man nciht den entsprechenden Kontext hat.

#Some ideas:#

* Ausblick auf künftig zu erwartende Entwicklungen, Hinweis auf mögliche weitere Forschung
* Handlungsanweisungen "Wie soll es weitergehen?"
* Lösen der erkannten Probleme
* Weitere, noch fehlende Daten hinzufügen
* Weiterentwickeln des PoC, bildet Grundlage zur Entscheidung, ob das Projekt weiterverfolgt werden soll
* Auch andere LLM-Modelle testen, z.B.
** Claude Haiku 4.5 (anderer Anbieter, andere Architektur)
** gpt-5-nano (klein, schnell, günstig, aber möglicherweise weniger leistungsfähig)
** gpt-5.4-mini (nachfloger con gpt-5-mini, teurer, vermutlich leistungsfähiger)
** gpt-5.4-nano (klein, günstig, schnell, neuer als gpt-5-nano)
* Evaluierung von Geschwindigkeitsverbesserungen. Aktuell ist der chatbot noch sehr langsam und brauch manchmal mehrere Minuten, um eine Antwort zu generieren
* Eine Liste von Prompts generieren und diese dann auf unterschiedliche Kriterien hin analysieren. Das würde das Problem lösen, dass eine Antwort zwar das zu testende Kriterium erfüllt, aber ein anderes verletzt.
** Nachteil: Die Antworten können pro Dorchgang unterschiedlich sein, löst das Problem also nicht wirklich
** Besser: Prüfen, ob neben Pass verschiedene Fail kriterien möglich sind. Pass: Alle passed: Fail: Liste der verletzten Kriterien/Kategorien. Ist das den Mehraufwand wert?

#Vielleicht macht es Sinn, in den jeweiligen Diskussionen schon verbesserungsvorschläge anzubringen und hier dann nur noch die wichtigsten oder für am einfachten Umsetzbar erachteten Vorschläge aufzuführen#
