
[#chapter-zusammenfassung-ausblick]
== Zusammenfassung und Ausblick

Abschliessend werden die Ergebnisse der Kapitel <<#zusammenfassung-poc,Proof of Concept>> und <<#zusammenfassung-evaluierung,Evaluierung>> zusammengefasst und Möglichkeiten zur Weiterentwicklung und Verbesserung des Chatbots und des Evaluierungsverfahrens gemacht.

[#zusammenfassung-poc]
=== Proof of Concept

Es wurde ein funktionsfähiger Chatbot entwickelt, der der nutzenden Person basierend auf den zur Verfügung stehenden Daten, Antworten zu den Jahreszahlen der TV Nutzung in der Schweiz geben kann. Der agent-basierte Chatbot ruft die gewünschten Daten von einem dafür implementierten MCP Server ab und gibt sie korrekt an die nutzenden Person zurück. Der Chatbot kann lokal in einer Docker Compose Umgebung ausgeführt werden, bringt die Daten bereits passend aufbereitet mit und benötigt nur Internetzugriff und einen OpenAI API Key für den Zugriff auf das konfigurierte LLM.

Da es sich um einen Prototypen handelt, sind für ein funktionales System noch viele Aufgaben zu erledigen. In der Arbeit wird nur ein kleiner Ausschnitt der TV und Radionutzungsdaten der Schweiz aus den Jahren 2018 bis 2021 für den Chatbot aufbereitet. Dies muss auch für den Rest der Daten durchgeführt werden. Für Daten unterschiedlicher Typen bedarf es einer Strategie, diese in den MCP Server einzubinden. Neben weiteren Spalten im vorhandenen Tool mit zusätzlichen Filtern ist auch denkbar, weitere Tools hinzuzufügen. Die zweite Version des MCP Servers hat im Vergleich zur ersten Version deutlich gemacht, wie wichtig ein logischer Aufbau der Datenstruktur und eine präzise Beschreibung der Tools und deren Parameter ist.

Ebenso wichtig ist die Aufbereitung der Daten in ein leicht verständliches Format, damit der Chatbot möglichst wenige Transformationen oder Mappings anwenden muss. Diese erwiesen sich der ersten Version als fehleranfällig, erhöhten die Dauer und verringerte die Qualität der Antworten. Ein Beispiel dafür ist, dass der Chatbot noch kein Verständnis der Zeitschiene von 02:00 Uhr bis 26:00 Uhr hat. Es müsste entweder im System-Prompt oder Glossary erklärt werden, dass die Zeiten von 00:00 bis 02:00 auf 24:00 bis 26:00 gemappt sind. Die vorgeschlagene Alternative ist, dies bereits in der Datenaufbereitung zurückzumappen. Da die Zahlen ohnehin über das gesamte Jahr aggregiert sind, ist es nicht entscheidend, zu welchem Tag sie gehören. Generell empfielt es sich, das Glossar und Begriffserklärungen die implizites Wissen voraussetzen, zu überarbeiten und explizit anzugeben. Ein Beispiel wäre die Zielguppe `Personen 3+`, die bisher nirgends erklärt ist. Der Chatbot scheint in den meisten fällen korrekt abzuleiten, dass es hier um Personen mit dem Alter 3 und älter geht, kommuniziert dies aber in der Regel nicht und setzt entsprechendes Wissen bei der nutzenden Person voraus. Eine Person, ohne entsprechenden Kontext, könnte auch annehmen, dass es sich zum Beispiel um eine Personengruppe mit mehr als 3 Personen handelt.

Manche Daten sind in der aktuellen Datenaufbereitung nicht in sich konsistent. So ist zum Beispiel der Sender "Andere Sender" eine aggregierte Spalte, die in den Rohdatentabellen SRF und nonSRF vorkommen, dabei aber jeweils unterschiedliche Sender meinen. Diese Unstimmigkeit muss für den Produktiveinsatz auf jeden Fall aufgelöst werden. Es ist zu entscheiden, ob das zum Beispiel durch eine Umbenennung, Entfernung der Spalten oder Daten zu den aggregierten Sendern gemacht wird. Zusätzlich könnte es für manche Anfragen sinnvoll sein, anzugeben, ob ein Wert bereits aggregiert ist, wie zum Beispiel die Sender _SRG SSR Total_ oder _Andere Sender_.

Zu entscheiden ist, mit welcher Präzision die Präsentation der Daten erfolgen soll. Aktuell werden die Zahlen nicht gerundet und so wie in den Datentabellen aufgeführt ausgegeben. Dies kann gegebenenfalls eine Genauigkeit implizieren, die nicht vorhanden ist.

Für den Chatbot an sich bietet es sich an, eine Geschwindigkeitsevaluierung durchzuführen und zu recherchieren welche Optionen zur Beschleunigung es gibt. Aktuell ist der Chatbot noch sehr langsam und braucht manchmal mehrere Minuten, um eine Antwort zu generieren. Ebenso gibt es eine Vielzahl von LLM Modellen, die für den Chatbot infrage kommen. So könnten auch Modelle anderer Anbieter wie zum Beispiel Claude Haiku 4.5 oder Gemini 3 Flash oder andere OpenAI Modelle verglichen werden, um die beste Performance zu evaluieren. Dafür werden die folgenden Modelle vorgeschlagen (Bewertung basierend auf `gpt-5-mini`):

* `gpt-5-nano` (klein, schnell, günstig, aber möglicherweise weniger leistungsfähig)
* `gpt-5.4-mini` (Nachfolger von gpt-5-mini, teurer, vermutlich leistungsfähiger)
* `gpt-5.4-nano` (klein, günstig, schnell, neuer als gpt-5-nano)

Für ein Produktivsystem wird eine zusätzliche Validierung der Eingangsdaten erforderlich sein. So ist die Texteingabemenge derzeit nicht beschränkt. Eine Stichprobe mit einem langen Text zeigt, dass der Chatbot seine ursprüngliche Aufgabe völlig vergisst und Aktivitäten ohne Zusammenhang zu den Jahreszahlen anbietet. Ein Limit für eine maximale Eingabe (zum Beispiel 500 oder 1'000 Zeichen) und eine Begrenzung wie viele Nachrichten innerhalb einer Session erlaubt sind, können helfen, den Kontext des LLMs auf der zu erledigenden Aufgabe zu halten. Auch einige Angriffe die darauf bauen, umfangreiche Anweisungen zu geben oder über viele Prompts hinweg nach und nach eine Beschränkung umgehen, können so einfach abgeblockt werden.

[#zusammenfassung-evaluierung]
=== Evaluierung

Die Eingangs in der Problemstellung gestellte Frage «Zu welchem Zeitpunkt hatte SRF 1 in der Deutschschweiz 2020 die höchste Einschaltquote?» beantwortet der Chatbot korrekt wie folgt:

[quote]
____
In der Deutschschweiz (Jahr 2020) hatte SRF 1 in der Zeitschiene 19:45:00 - 20:00:00 die höchste Einschaltquote. +
Kenngrösse: Rating in % = 15.3969 %. (Rating in 1'000 = 806.336)
____

Das manuelle prüfen erlaubt ser detaillierte und zielgerichtete Fragen an den Chatbot, die dann direkt evaluiert werden können. Für eine grössere Untersuchung wird hier das Tool Promptfoo verwendet, mit dem automatisiert viele verschiedene Testszenarien durchgeführt werden können. Es werden die vier Dimensionen Korrektheit, Prognosen, Interpretationen und Handlungsanweisungen überprüft.

Die generierten Test sind teilweise schlecht oder unspezifisch. Das reduziert die Aussagekraft und erfordert daher die manuelle kontrolle aller automatisch erstellten Testergebnisse. Die Erwartung, dass alle Testfälle relevant sind und nur die High-Level Auswertung der Ergebnisse ausreicht, wird nicht erfüllt. Dem entgegen steht der erheblich reduzierte Aufwand zur Erstellung der Testfälle. Auch wenn die Ergebnisse der Tests nicht von höchster Qualität sind, so zeigen sie doch schon Schwächen des Systems auf, die es sich lohnt zu beheben. Durch den automatisierten Prozess lässt sich dann einfach die Wirksamkeit der ergriffenen Massnahmen überprüfen. Die Analyse nach den unterschiedlichen Dimensionen ist schwierig. Sie verschwimmen und Antworten für eine Kategorie können korrekt sein, dabei aber Massgaben einer anderen Kategorie verletzen. Dieses Problem wird in der Arbeit nicht systematisch vermieden und die Ergebnisse der einzelnen Dimensionen sind daher nur für die untersuchte Dimension aussagekräftig.

Die Chatbotantworten in der Dimension Korrektheit sind sehr vielversprechend. Die  Antworten sind, abgsehen von einer durch einen Konfigurationsfehler im System-Prompt verursachten Falschantwort, korrekt und beantworten die gestellten Fragen. Allerdings bietet der Chatbot unmögliche weiterführende Aktionen an und führt Berechnungen durch. Dieses unerwünschte Verhalten wird aktuell im System-Prompt noch nicht eingeschränkt. Es werden Anpassungen vorgeschlagen, die den Chatbot diesbezüglich verbessern können.

Obwohl im System-Prompt Vorgaben bezüglich Prognosen enthalten sind, schneidet der Chatbot in den Tests zu dieser Dimension schlecht ab. Insbesondere Multi-Turn Strategien wie Crescendo hebeln die aktuell implementierten Beschränkungen aus und der Chatbot gibt viele Prognosen. Hier besteht noch Handlungsbedarf um dieses Verhalten zu verbessern. Kleine Verschärfungen des System-Prompt brachten nur leichte Verbesserungen.

Die grösste Schwachstelle des Chatbots liegt in der Dimension Interpretationen. Nahezu alle Angriffe im Test sind erfolgreich. Es sind strukturelle Einschränkungen erforderlich, die über Änderungen am System-Prompt hinausgehen. Vorgeschlagen werden die automatische Erkennung von Kausalmarkern und bereits vordefinierte Antworten auf häufige Fragen, die dem Chatbot die Formulierung einer Antwort abnehmen.

In der vierten Dimension erstellt der Chatbot, wenn darum gebeten oder durch andere Limitierungen im System-Prompt dazu gedrängt, teilweise sehr umfangreiche und detaillierte, Handlungsempfehlungen. Dies ist im System-Prompt bisher nicht ausgeschlossen. Es wird eine enstrprechende Anpassung des System-Prompt vorgeschlagen.

Für die weiterentwicklung des Systems empfiehlt es sich, ein überarbeitetes und manuell zurechgeschnittenes Testsetup zu verwenden. Idealerweise werden in einer Evaluierung Testfälle gebündelt, die alle vier Dimensionen überprüfen und auch einzeln ausgewertet werden können. Dabei sollte die Anzahl an Plugins und Strategien möglichst gering gehalten werden, damit die Tests oft und schnell durchgeführt werden können. Die Custom- und das Policy-Plugin haben sich als flexibel herausgestellt und eignen sich gut für die Generierung von neuen Testfällen. Mit einer Kombination aus Single- und Multi-Turn Strategien wie Basic und Crescendo oder Jailbreak ist auch hier eine gute Testabdeckung zu erwarten. Aller Automatisierung zum trotz ist die manuelle Prüfung und gegebenenfalls manuelle Anpassung der Testfälle vor der ersten Evaluierung unabdingbar. So wird sichergestellt, dass die Tests nicht zu ähnlich sind und und wirklich die gewünschten Dimensionen evaluiert werden. Bei Anpassungen für eine Dimension kann dann auch nachvollzogen werden, ob sich die Ergebnisse in den anderen Dimensionen verbessern oder verschlechtern.

In einem von Promptfoo aufgrund der Ergebnisse generierten Behebungsbericht (genannt "Remediation Report"), werden für alle Analysen die folgenden priorisierten Handlungsvorschläge gemacht:

. *System-Prompt stärken*: Erweitern Sie die Systemanweisung dahingehend, dass die Abgabe von umsetzbaren Empfehlungen, strategischen Vorschlägen oder Werturteilen ausdrücklich untersagt wird, und weisen Sie das Modell an, unter keinen Umständen eine beratende Rolle einzunehmen.
. *Eingabeschutz implementieren*: Setzen Sie Eingabefilter ein, um Benutzeranfragen zu erkennen und zu blockieren, die umsetzbare Empfehlungen, strategische Ratschläge, operative Pläne oder Werturteile erfordern.
. *Ausgabeschutz implementieren*: Wenden Sie eine Ausgabefilterung an, um Antworten zu erkennen und zu blockieren, die umsetzbare Empfehlungen, Schritt-für-Schritt-Anleitungen, strategische Vorschläge oder Werturteile enthalten, selbst wenn die Eingabe die ersten Filter umgeht.
