
[#chapter-zusammenfassung-ausblick]
== Zusammenfassung und Ausblick

#ToDo: umstrukturieren: je ein Abschnitt für PoC und Red Teaming#

=== Proof of Concept

Es wurde ein funktionsfähiger Chatbot entwickelt, der der nutzenden Person basierend auf den zur Verfügung stehenden Daten, Antworten zu den Jahreszahlen der TV Nutzung in der Schweiz geben kann. Der agent-basierte Chatbot ruft die gewünschten Daten von einem dafür implementierten MCP Server ab und gibt sie korrekt an die nutzenden Person zurück. Der Chatbot kann lokal in einer Docker Compose Umgebung ausgeführt werden, bringt die Daten bereits passend aufbereitet mit und benötigt nur Internetzugriff und einen OpenAI API Key für den Zugriff auf das konfigurierte LLM.

Da es sich um einen Prototypen handelt, sind für ein funktionales System noch viele Aufgaben zu erledigen. In der Arbeit wird nur ein kleiner Ausschnitt der TV und Radionutzungsdaten der Schweiz aus den Jahren 2018 bis 2021 für den Chatbot aufbereitet. Dies muss auch für den Rest der Daten durchgeführt werden. Für Daten unterschiedlicher Typen bedarf es einer Strategie, diese in den MCP Server einzubinden. Neben weiteren Spalten im vorhandenen Tool mit zusätzlichen Filtern ist auch denkbar, weitere Tools hinzuzufügen. Die zweite Version des MCP Servers hat im Vergleich zur ersten Version deutlich gemacht, wie wichtig ein logischer Aufbau der Datenstruktur und eine präzise Beschreibung der Tools und deren Parameter ist.

Ebenso wichtig ist die Aufbereitung der Daten in ein leicht verständliches Format, damit der Chatbot möglichst wenige Transformationen oder Mappings anwenden muss. Diese erwiesen sich der ersten Version als fehleranfällig, erhöhten die Dauer und verringerte die Qualität der Antworten. Ein Beispiel dafür ist, dass der Chatbot noch kein Verständnis der Zeitschiene von 02:00 Uhr bis 26:00 Uhr hat. Es müsste entweder im System-Prompt oder Glossary erklärt werden, dass die Zeiten von 00:00 bis 02:00 auf 24:00 bis 26:00 gemappt sind. Die vorgeschlagene Alternative ist, dies bereits in der Datenaufbereitung zurückzumappen. Da die Zahlen ohnehin über das gesamte Jahr aggregiert sind, ist es nicht entscheidend, zu welchem Tag sie gehören. Generell empfielt es sich, das Glossar und Begriffserklärungen die implizites Wissen voraussetzen, zu überarbeiten und explizit anzugeben. Ein Beispiel wäre die Zielguppe `Personen 3+`, die bisher nirgends erklärt ist. Der Chatbot scheint in den meisten fällen korrekt abzuleiten, dass es hier um Personen mit dem Alter 3 und älter geht, kommuniziert dies aber in der Regel nicht und setzt entsprechendes Wissen bei der nutzenden Person voraus. Eine Person, ohne entsprechenden Kontext, könnte auch annehmen, dass es sich zum Beispiel um eine Personengruppe mit mehr als 3 Personen handelt.

Manche Daten sind in der aktuellen Datenaufbereitung nicht in sich konsistent. So ist zum Beispiel der Sender "Andere Sender" eine aggregierte Spalte, die in den Rohdatentabellen SRF und nonSRF vorkommen, dabei aber jeweils unterschiedliche Sender meinen. Diese Unstimmigkeit muss für den Produktiveinsatz auf jeden Fall aufgelöst werden. Es ist zu entscheiden, ob das zum Beispiel durch eine Umbenennung, Entfernung der Spalten oder Daten zu den aggregierten Sendern gemacht wird. Zusätzlich könnte es für manche Anfragen sinnvoll sein, anzugeben, ob ein Wert bereits aggregiert ist, wie zum Beispiel die Sender _SRG SSR Total_ oder _Andere Sender_.

Zu entscheiden ist, mit welcher Präzision die Präsentation der Daten erfolgen soll. Aktuell werden die Zahlen nicht gerundet und so wie in den Datentabellen aufgeführt ausgegeben. Dies kann gegebenenfalls eine Genauigkeit implizieren, die nicht vorhanden ist.

Für den Chatbot an sich bietet es sich an, eine Geschwindigkeitsevaluierung durchzuführen und zu recherchieren welche Optionen zur Beschleunigung es gibt. Aktuell ist der Chatbot noch sehr langsam und braucht manchmal mehrere Minuten, um eine Antwort zu generieren. Ebenso gibt es eine Vielzahl von LLM Modellen, die für den Chatbot infrage kommen. So könnten auch Modelle anderer Anbieter wie zum Beispiel Claude Haiku 4.5 oder Gemini 3 Flash oder andere OpenAI Modelle verglichen werden, um die beste Performance zu evaluieren. Dafür werden die folgenden Modelle vorgeschlagen (Bewertung basierend auf `gpt-5-mini`):

* `gpt-5-nano` (klein, schnell, günstig, aber möglicherweise weniger leistungsfähig)
* `gpt-5.4-mini` (Nachfolger von gpt-5-mini, teurer, vermutlich leistungsfähiger)
* `gpt-5.4-nano` (klein, günstig, schnell, neuer als gpt-5-nano)

Für ein Produktivsystem wird eine zusätzliche Validierung der Eingangsdaten erforderlich sein. So ist die Texteingabemenge derzeit nicht beschränkt. Eine Stichprobe mit einem langen Text zeigt, dass der Chatbot seine ursprüngliche Aufgabe völlig vergisst und Aktivitäten ohne Zusammenhang zu den Jahreszahlen anbietet. Ein Limit für eine maximale Eingabe (zum Beispiel 500 oder 1'000 Zeichen) und eine Begrenzung wie viele Nachrichten innerhalb einer Session erlaubt sind, können helfen, den Kontext des LLMs auf der zu erledigenden Aufgabe zu halten. Auch einige Angriffe die darauf bauen, umfangreiche Anweisungen zu geben oder über viele Prompts hinweg nach und nach eine Beschränkung umgehen, können so einfach abgeblockt werden.

=== Evaluierung

==== Zusammenfassung

Die Eingangs in der Problemstellung gestellte Frage «Zu welchem Zeitpunkt hatte SRF 1 in der Deutschschweiz 2020 die höchste Einschaltquote?» beantwortet der Chatbot korrekt wie folgt:

[quote]
____
In der Deutschschweiz (Jahr 2020) hatte SRF 1 in der Zeitschiene 19:45:00 - 20:00:00 die höchste Einschaltquote. +
Kenngrösse: Rating in % = 15.3969 %. (Rating in 1'000 = 806.336)
____

Die Evaluierung der Korrektheit der Chatbotantworten ist sehr vielversprechend. Die zurückgegebenen Antworten sind, abgsehen von einem Konfigurationsfehler im System-Prompt, korrekt und beantworten die gestellten Fragen. Der Chatbot bietet unmögliche, weiterführende Aktionen an und führt Berechnungen durch. Dieses unerwünschte Verhalten wird aktuell im System-Prompt noch nicht eingeschränkt. Es werden Anpassungen vorgeschlagen, die den Chatbot diesbezüglich verbessern können.

* #ToDo: Ergebnisse prognosen#
* #ToDo: Ergebnisse Interpretationen#

Wenn darum gebeten oder durch andere Limitierungen im System-Prompt dazu gedrängt, erstellt der Chatbot, teilweise sehr umfangreiche und detaillierte, Handlungsempfehlungen. Dies ist im System-Prompt bisher nicht ausgeschlossen. Es wird eine enstrprechende Anpassung des System-Prompt vorgeschlagen.

* Chatbot wird kreativ um die Useranfragen im Rahmen seiner Möglichkeiten zu erledigen
* Die generierten Test sind teilweise schlecht oder unspezifisch. Das reduziert die Aussagekraft und macht die Auswertung sehr zeitaufwendig, da die Tests alle einzeln analysiert werden müssen. Die Erwartung, dass alle Testfälle super relevant sind und nur die High-Level Auswertung der Ergebnisse reicht, wird nicht erfüllt. Dem entgegenzuhalten ist der erheblich reduzierte Aufwand, der für die Ergebnisse betrieben werden muss. Auch wenn die Ergebnisse der Tests nicht von höchster Qualität sind, so zeigen sie doch schon Schwächen des Systems auf, die es sich lohnt zu beheben. Durch den automatisierten Prozess lässt sich dann einfach die Wirksamkeit der ergriffenen Massnahmen überprüfen.
* Die Analyse nach den unterschiedlichen Kategorien ist sehr schwer, sie verschwimmen und Antworten für eine Kategorie zwar korrekt sein können, dabei aber Massgaben einer anderen Kategorie verletzen. Dieses Problem wurde in dieser Arbeit aus Aufwandsgründen nicht näher betrachtet und die Ergebnisse können durch diesen Effekt verzerrt sein.

==== Ausblick

* Eine Liste von Prompts generieren und diese anschliessend auf unterschiedliche Kriterien hin zu analysieren. Das würde das Problem lösen, dass eine Antwort zwar das zu testende Kriterium erfüllt, aber ein anderes verletzt.
** Nachteil: Die Antworten können pro Durchgang unterschiedlich sein, löst das Problem also nicht wirklich.
** Besser: Prüfen, ob neben Pass verschiedene Fail kriterien möglich sind. Pass: Alle passed: Fail: Liste der verletzten Kriterien/Kategorien. Ist das den Mehraufwand wert?
* Generelle Untersuchung auf Risiken von LLM Applikationen, siehe cite:[owaspLlmTop10]


#ToDo: Der Teil hier wird bei allen Tests vorgeschlagen und passt daher besser in eine allgemeine Sektion wie das Fazit#
Promptfoo bietet die Möglichkeit, für die durchgeführten Analysen einen Behebungsbericht (genannt "Remediation Report") zu erstellen. In diesem werden die wie folgt priorisierten Handlungsitems vorgeschlagen:

. *Systempromt stärken*: Erweitern Sie die Systemanweisung dahingehend, dass die Abgabe von umsetzbaren Empfehlungen, strategischen Vorschlägen oder Werturteilen ausdrücklich untersagt wird, und weisen Sie das Modell an, unter keinen Umständen eine beratende Rolle einzunehmen. Damit werden direkt die Schwachstellen behoben, bei denen das LLM auch nach wiederholten oder umformulierten Nutzeranfragen Schritt-für-Schritt-Pläne oder strategische Ratschläge ausgibt.
. *Eingabeschutz implementieren*: Setzen Sie Eingabefilter ein, um Benutzeranfragen zu erkennen und zu blockieren, die umsetzbare Empfehlungen, strategische Ratschläge, operative Pläne oder Werturteile erfordern. Dadurch wird verhindert, dass das LLM Anfragen verarbeitet, die wahrscheinlich zu unzulässigen Ausgaben führen, insbesondere solche, bei denen Social-Engineering- oder iterative Jailbreak-Techniken zum Einsatz kommen.
. *Ausgabeschutz implementieren*: Wenden Sie eine Ausgabefilterung an, um Antworten zu erkennen und zu blockieren, die umsetzbare Empfehlungen, Schritt-für-Schritt-Anleitungen, strategische Vorschläge oder Werturteile enthalten, selbst wenn die Eingabe die ersten Filter umgeht. Dadurch wird sichergestellt, dass eingeschränkte Inhalte der nutzenden Person nicht bereitgestellt werden, selbst bei mehrstufigen oder iterativen Angriffsszenarien.
. *Enforce Access Controls*: Beschränken Sie den Zugriff auf erweiterte LLM-Funktionen und sensible Datenausgaben ausschliesslich auf autorisierte Benutzer. Dadurch wird das Risiko eines Missbrauchs verringert, indem eingeschränkt wird, wer mit dem System in einer Weise interagieren kann, die zu unerwünschten Ausgaben führen könnte -- insbesondere in einer selbst gehosteten oder benutzerdefinierten Umgebung.
